---
# ©Copyright 2015-2016 Hewlett Packard Enterprise Development Company, LP

- include: pip_index.yml

- name: Install deps to avoid pip doing compilation or enable it
  apt: name={{item}} state=present
  with_items: dependencies_deb
  when: ansible_os_family == 'Debian'
  
- name: Install rpms to avoid pip doing compilation or enable it
  yum: name={{item}} state=present
  with_items: dependencies_rpm
  when: ansible_os_family == 'RedHat'

- name: Upgrade pip in virtualenv
  pip: name=pip version=7.1.2 virtualenv="{{monasca_virtualenv_dir}}"

- name: pip install latest monasca-agent in a virtualenv
  pip: name=monasca-agent state=latest virtualenv="{{monasca_virtualenv_dir}}"
  notify: run monasca-setup
  when: monasca_agent_version is not defined

- name: pip install a specific version of monasca-agent in a virtualenv
  pip: name=monasca-agent state=present version="{{monasca_agent_version}}" virtualenv="{{monasca_virtualenv_dir}}"
  notify: run monasca-setup
  when: monasca_agent_version is defined

- name: pip install psutil==3.0.1
  pip: name=psutil version=3.0.1 virtualenv="{{monasca_virtualenv_dir}}"
  notify: run monasca-setup
