---
# ©Copyright 2015 Hewlett-Packard Development Company, L.P.

- name: Include system dependencies
  include_vars: "vars{{ ansible_os_family }}.yml"

- name: Include DB dependencies
  include_vars: "{{ ansible_os_family|lower }}_{{ database_backend }}.yml"
  when: database_support

- name: Install deps to avoid pip doing compilation
  yum: name={{item}} state=present
  with_items: dependencies
  when: not skip_install and ansible_os_family == "RedHat"

- name: Install deps to avoid pip doing compilation
  apt: name={{item}} state=present
  with_items: dependencies
  when: not skip_install and ansible_os_family == "Debian"

- name: Install DB dependencies (RedHat)
  yum: name={{item}} state=present
  with_items: database_dependencies
  when: not skip_install and ansible_os_family == "RedHat" and (install_yum_postgres_lib is defined and install_yum_postgres_lib)

- name: Install DB dependencies (Debian)
  apt: name={{item}} state=present update_cache=yes
  with_items: database_dependencies
  when: not skip_install and ansible_os_family == "Debian"

- include: pip_index.yml
  when: not skip_install

- name: pip install virtualenv
  pip: name=virtualenv version=13.1.2
  when: not skip_install

- name: pip install pymysql
  pip: name=pymysql version="0.7.10" virtualenv="{{monasca_virtualenv_dir}}"
  when: not skip_install

- name: Install SQLAlchmy for postgresql
  pip: name=sqlalchemy version="1.0.17" virtualenv="{{monasca_virtualenv_dir}}"
  notify:
    - restart monasca-notification
  when: database_backend == 'postgresql'

- name: pip install dependencies in virtualenv
  pip: name={{ item.name }} version={{ item.version }}
  with_items:
    - name: greenlet
      version: "0.4.11"
    - name: gevent
      version: "1.2.1"
    - name: pykafka
      version: "2.5.0"
    - name: monasca-common
      version: "1.5.0"
    - name: monasca-statsd
      version: "1.5.0"

- name: pip install monasca-notification
  pip: name="{{monasca_notification_name}}" version="1.6.0" virtualenv="{{monasca_virtualenv_dir}}"
  notify:
    - restart monasca-notification
  when: not skip_install

