---
# ©Copyright 2015 Hewlett-Packard Development Company, L.P.

- name: OpenStack Alarm definitions
  monasca_alarm_definition:
    name: "{{item.name}}"
    description: "{{item.description | default('') }}"
    expression: "{{item.expression}}"
    keystone_token: "{{default_notification.keystone_token}}"
    match_by: "{{item.match_by | default(['hostname']) }}"
    monasca_api_url: "{{default_notification.monasca_api_url}}"
    severity: "{{item.severity | default('LOW') }}"
    alarm_actions:
      - "{{default_notification.notification_method_id}}"
    ok_actions:
      - "{{default_notification.notification_method_id}}"
    undetermined_actions:
      - "{{default_notification.notification_method_id}}"
  with_items:
    - { name: "Instance CPU Usage", description: "Alarms when the CPU usage of the specified instance is high", expression: "avg(cpu.utilization_perc) > 90 times 3", match_by: [resource_id] }
