---
- include: DebianInst.yml
  when: "ansible_os_family == 'Debian'"

- include: RedHatInst.yml
  when: "ansible_os_family == 'RedHat'"

- name: Fetch storm package
  get_url: dest={{ download_tmp_dir }}/apache-storm-{{storm_version}}.tar.gz url="{{apache_mirror}}/storm/apache-storm-{{storm_version}}/apache-storm-{{storm_version}}.tar.gz"
