---
- name: Stop Supervisor
  service: name=storm-supervisor state=stopped enabled=yes

- name: Stop Logviewer
  service: name=storm-logviewer state=stopped enabled=yes
  when: storm_logviewer_enabled
