---
galaxy_info:
  author: Tim Kuhlman
  description: Installs the monasca-api part of the Monasca project.
  company: HP
  license: Apache
  min_ansible_version: 1.7
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  - name: Debian
    versions:
    - jessie
  - name: RedHat
    versions:
    - all
  categories:
  - monitoring
dependencies: []
