---
# ©Copyright 2015 Hewlett-Packard Development Company, L.P.

#- name: pip install requirements
#  pip:
#    requirements: /my_app/requirements.txt
#    virtualenv: /my_app/venv
#    extra_args: -i https://example.com/pypi/simple

- name: create monasca virtualenv dir
  file: path={{ monasca_virtualenv_dir }} state=directory owner=root group=root mode=755

- name: pip install gunicorn in virtualenv
  pip: name=gunicorn version={{ monasca_gunicorn_version }} virtualenv={{ monasca_virtualenv_dir }}

- name: pip install influxdb in virtualenv
  pip: name=influxdb version={{ monasca_influxdb_version }} virtualenv={{ monasca_virtualenv_dir }}

- name: pip install dependencies in virtualenv
  pip: name={{ item.name }} version={{ item.version }}
  with_items:
    - name: greenlet
      version: "0.4.11"
    - name: gevent
      version: "1.2.1"
    - name: pykafka
      version: "2.5.0"
    - name: monasca-common
      version: "1.5.0"
    - name: eventlet
      version: "0.20.1"
    - name: falcon
      version: "1.1.0"

- name: pip install monasca-api in virtualenv
  pip: name=monasca-api version={{ monasca_api_version }} virtualenv={{ monasca_virtualenv_dir }}
