---
# ©Copyright 2015 Hewlett-Packard Development Company, L.P.

- name: pip install pykafka in virtualenv
  pip: name=pykafka version="2.5.0" virtualenv={{ monasca_virtualenv_dir }}

- name: pip install monasca-perister in virtualenv
  pip: name=monasca-persister version={{ persister_version }} virtualenv={{ monasca_virtualenv_dir }}
  notify:
    - restart monasca-persister
